### ISSUE TITLE
Add support to build for Windows 11 ARM64 

### ISSUE THREAD

**Issue by ppauquette-mwb** [getsentry/sentry-native#988] opened 2024-05-16 20:27 UTC
### Problem Statement

We want to build Sentry for Windows 11 ARM64 with Visual Studio. We are seeing a growing market for our service amongst ARM64 laptops.

### Product Area

Projects - Project Creation

**Comment by supervacuus** [comment] 2024-05-17 07:22
Hi @ppauquette-mwb. As mentioned here: https://github.com/getsentry/sentry-native/issues/880#issuecomment-1977386854, if you use the Native SDK with the `crashpad` backend, you can already integrate it into your ARM64 Windows build. It looks like thebrowsercompany already deploys ARM64 Windows builds of the Arc browser using the Native SDK.

We can't officially support the build because our CI does not support Windows on ARM64 (even though it runs on Microsoft infrastructure). However, if you have any input regarding the ARM64 build of the Native SDK, please let us know.

I will close this issue as a duplicate of #880. Let's continue our discussion there, or if you have a particular problem, feel free to create a new issue.

**Closed by supervacuus** 2024-05-17 07:22 UTC
Labels: Waiting for: Product Owner
