### ISSUE TITLE
sysctlbyname kern.nx: No such file or directory and HTTP status 400 Errors

### ISSUE THREAD

**Issue by jonfk** [getsentry/sentry-native#219] opened 2020-04-03 14:54 UTC
I am trying out sentry for the first time and recently integrated the sentry native sdk with my rust 
application to find a segmentation fault that occurs infrequently.
I followed https://blog.sentry.io/2019/12/19/debugging-a-segfault-in-rust to integrate the native sdk in rust.
I just got the first segfault with sentry integrated into my code but sentry seems to have failed with the following errors:

```
[78536:4496179:20200403,104407.209850:WARNING system_snapshot_mac.cc:42] sysctlbyname kern.nx: No such file or directory (2)
make: *** [run] Segmentation fault: 11
[78536:4496182:20200403,104407.724498:ERROR http_transport_mac.mm:297] HTTP status 400
```

The segfault in the middle is my program segfaulting I believe.

I am using the 0.2.2 release of the sentry native sdk on osx with the following build commands
```
$ cmake -B build -DSENTRY_BACKEND=crashpad
$ cmake --build build --parallel
$ cmake --install build --prefix install --config Debug
```

**Comment by Swatinem** [comment] 2020-04-03 16:13
Both of those logs actually come from crashpad. Can you try with the inproc backend, just to make sure there is nothing wrong with with sentry-native itself?

**Comment by jonfk** [comment] 2020-04-03 17:58
Thanks I will try that

**Comment by jan-auer** [comment] 2020-04-03 18:00
No need to disable Crashpad. Let's bisect the log output line by line:

```
[WARNING system_snapshot_mac.cc:42] sysctlbyname kern.nx: No such file or directory (2)
```

This is due to a change in the latest macOS revisions and was fixed in Crashpad upstream via [`61a4f3d`](https://chromium.googlesource.com/crashpad/crashpad/+/61a4f3d7d6f65945e81aaffe701da75c60c3ff2d). Once we update our fork, this should go away.

```
make: *** [run] Segmentation fault: 11
```

This is the segfault that likely your program generates. What it is caused by can only be figured out by looking at the minidump. There is a tiny chance that this is caused by our SDK, but considering that you were debugging crashes it's more likely somewhere else.

```
[ERROR http_transport_mac.mm:297] HTTP status 400
```

This means that crashpad cannot upload the file to sentry.io. Are you potentially trying to use the SDK with Sentry onpremise? Also, could you please double-check that the DSN is correct?

**Comment by jonfk** [comment] 2020-04-03 18:12
Thanks for your reply @jan-auer.

1. Does the error from crashpad mean it's not causing the second error and can be disregarded for now?
2. I am not using Sentry onpremise. My dsn is correct from what I can tell since I was able to send the `It works!` example event that is provided in the onboarding page.

**Comment by Swatinem** [comment] 2020-04-05 08:17
@jan-auer in a different discussion, it came up that the crashpad attachments could potentially be 0B files, not sure if the server will reject those with a `400`?

**Comment by jan-auer** [comment] 2020-04-05 08:24
The server accepts empty attachments and should even show them in the UI. We did have issues with empty attachments in the past, but those have been fixed. 

The server responds with an error message that explain the exact reason for the 400, but straight up I do not know of a way to log that response in Crashpad.

**Closed** 2020-04-14 13:49 UTC
