### ISSUE TITLE
throw exception, crash report is not working

### ISSUE THREAD

**Issue by mohadangKim** [getsentry/sentry-native#582] opened 2021-07-22 05:15 UTC
**Description**

I made it run below code, but dose not report crash
when I test, I changed dsn

**When does the problem happen**

- [ ] During build
- [x] During run-time
- [ ] When capturing a hard crash

**Environment**

- OS: Windows 10, 64-bit
- Compiler: MSVC 19
- native, crashpad

**Steps To Reproduce**

```
void Func() {
	std::thread th1([]() {
		throw std::exception("custom exception");
	});
	th1.join();
}

int main(void) {
	sentry_options_t* options = sentry_options_new();
	sentry_options_set_dsn(options, " ~~~ ");
	sentry_init(options);
	std::cout << "Wait..." << std::endl;
	std::cin.get();
	Func();
	std::cin.get();
	sentry_close();
}
```

**Comment by Swatinem** [comment] 2021-07-27 08:03
I can’t really reproduce the failure.

Running your example, Windows presents a crash dialog to me, closing this, execution is handed over to crashpad again, which then sends a minidump to sentry. However we fail to correctly unwind through that exception stack trace, in particular we fail to unwind through `RtlDispatchException` which windbg can handle correctly.

![grafik](https://user-images.githubusercontent.com/580492/127118454-e6e36c10-ff99-4d96-a1e4-931a3781bf70.png)

**Comment by Swatinem** [comment] 2022-07-28 11:23
I have just tried the code again and this seems to now be fixed since we implemented https://github.com/getsentry/symbolic/issues/546

**Closed by Swatinem** 2022-07-28 11:23 UTC
