### ISSUE TITLE
Sentry Native Android SDK Crashing - sentry__string_eq Unhandled Segfault

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry-native#859] opened 2023-06-28 13:07 UTC
**Description**

Message me @Will in Slack for link to the Customer's Issue in Sentry.

**When does the problem happen**

- [ ] During build
- [ x] During run-time
- [ ] When capturing a hard crash

**Environment**

**Steps To Reproduce**
The issue in sentry has this on it:

err.type looks like sentry__string_eq

it also says Unhandled Segfault

and

<img width="491" alt="image" src="https://github.com/getsentry/sentry-native/assets/8920574/63c9d489-0adc-4586-ba27-4653783ae8c1">

**Log output**
no additional log output

**Comment by will** [comment] 2023-06-28 13:54
I would but I don’t think I’m in a slack with you On Jun 28, 2023, at 15:07, William Capozzoli ***@***.***> wrote:﻿
Description
Message me @will in Slack for link to the Customer's Issue in Sentry.
When does the problem happen

 During build
[ x] During run-time
 When capturing a hard crash

Environment
Steps To Reproduce
The issue in sentry has this on it:
err.type looks like sentry__string_eq
it also says Unhandled Segfault
and

Log output
no additional log output

**Comment by supervacuus** [comment] 2023-06-29 06:15
Hi, thanks for the report. I can gather from the stack trace that this must have been in a `sentry-android` version that came bundled with `sentry-native` < `0.6.2`. The segfault comes from passing `NULL` to `strcmp()` inside `sentry__string_eq()`. 

Adding ptr/len interfaces to the API, I rewrote many string functions and specifically added early checks for `NULL`s. Especially the code in `sentry_value_set_by_key()` has been made safer. This was released with `sentry-android` `6.19.0`.

**Comment by thinkocapo** [comment] 2023-06-29 09:40
is the suggestion to upgrade to 6.19.0?  If so, what is the the new expected behavior? So I can communicate back to the customer.

For example:
1. upgrade to 6.19.0
2. the sdk should not error on itself anymore, therefore no event for sending to Sentry.io.
3. or
4. upgrade to 6.19.0
5. the sdk might still error on itself, but the event will not get sent to Sentry.io? the sdk will fail more silently this time?

**Comment by supervacuus** [comment] 2023-06-29 17:03
I would always recommend upgrading if there seems to be a bug in an SDK because we do not maintain separate release branches, so even if there is still an issue in the latest release, I can only supply a fix on top of that. Going deeper, this stack trace is probably from version `0.4.18` of the Native SDK, released over a year ago (and packaged with `sentry-android 6.3.1`).

The crash in the Native SDK is probably caused by the same memory corruption which caused the application to crash in the first place. We can make sure that we don't crash in that particular situation. However, the resulting crash event will still be affected by that. The stack trace shows that the segfault occurs when setting the `event_id` of the crash-event, meaning that either the constant string "event_id" is NULL or that the event internal structure has been corrupted, leaving us to try to iterate over non-existent key/value pairs of a fresh object (which has no entries yet). 

What I mean by that: fingers crossed that we can send a halfway decent crash report in that case. Understanding how that situation is possible would be interesting, but I cannot gather that from the stack trace. Maybe @Swatinem can look at the event and check if he sees something relevant.

**Closed as not planned** 2024-12-10 18:12 UTC
Labels: Bug
