### ISSUE TITLE
Crash report not associated release

### ISSUE THREAD

**Issue by conradjones** [getsentry/sentry-native#73] opened 2019-10-24 20:41 UTC
The crash report (minidump) uploaded to sentry (on prem) via crashpad_handler on windows isn't associated with the release, I'm also uploading the "it works" example event inside the program and this is associated with the release.

**Comment by mitsuhiko** [comment] 2019-11-21 10:49
Closing this as duplicate of #84

**Closed by mitsuhiko** 2019-11-21 10:49 UTC
