### ISSUE TITLE
Build fails on gcc 11

### ISSUE THREAD

**Issue by MisterTea** [getsentry/sentry-native#501] opened 2021-03-24 03:59 UTC
**Description**

Someone is reporting a sentry compile error on gcc 11: https://github.com/MisterTea/EternalTerminal/issues/412

**Comment by jubalh** [comment] 2021-11-03 15:20
It seems that a newer libc is defining SIGSTKSZ as long int?
The problem is that 
https://github.com/getsentry/breakpad/blob/master/src/client/linux/handler/exception_handler.cc#L141 is now comparing an int with an long int and max() expects both to be the same type.
Casting solves the error. Though I'm unsure this is the best solution.

**Comment by jubalh** [comment] 2021-11-10 10:32
Fix merged to the `handler` branch.

**Comment by Swatinem** [comment] 2021-12-21 12:14
We recently made a new release that should include the breakpad fix.

**Closed by Swatinem** 2021-12-21 12:14 UTC
